export const HEADER_MODAL_OPEN = 'HEADER_MODAL_OPEN';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_MODAL_CLOSE = 'SIGNUP_MODAL_CLOSE';
export const SIGNUP_TAB_CHANGE = 'SIGNUP_TAB_CHANGE';
export const SIGNUP_SNACKBAR_CLOSE='SIGNUP_SNACKBAR_CLOSE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SET_REDIRECT_PATH = 'SET_REDIRECT_PATH';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_START = 'LOGOUT_START';

export const RESET_LOGIN_STATE = 'RESET_LOGIN_STATE';

export const SET_FILTER_TEXT='SET_FILTER_TEXT';