export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_MODAL_CLOSE = 'SIGNUP_MODAL_CLOSE';
export const SIGNUP_TAB_CHANGE = 'SIGNUP_TAB_CHANGE';
export const SIGNUP_SNACKBAR_CLOSE='SIGNUP_SNACKBAR_CLOSE';